

spring.profiles.active: development

---

spring:
  profiles: development

  datasource.url: jdbc:h2:mem:dev
  datasource.username: sa
  datasource.password:
  datasource.driver-class-name: org.h2.Driver

---

spring:
  profiles: test

  datasource.url: jdbc:h2:mem:ftc-test-db
  datasource.username: sa
  datasource.password:
  datasource.driver-class-name: org.h2.Driver

